language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-koto' ]; then cd .. && eval "mv $currentfolder generator-koto" && cd generator-koto; fi
